### ISSUE TITLE
hard to find info about MFCC parameters

### ISSUE THREAD

**Issue by marikgoldstein** [tbertinmahieux/MSongsDB#8]
The million song dataset website links to echonest for more details about the extracted features from the audio, but the echonest developers page has since gone down I believe.

Is there any information about the original FFT parameters used to compute the segments_timbre feature? What does a "segment" mean exactly? Which mel coefficients were used and which contributed to the principle components used?

Is this information lost?

Thank you!

**Comment by dpwe** [comment]
The Internet Archive holds copies of the old Echo Nest pages, e.g.
http://web.archive.org/web/*/http://developer.echonest.com/docs/v4/

The MSD timbre features are not MFCCs, and they are not easily described by
parameters such as window length.  Basically, Echo Nest Analyze segmented
the audio into variable-length chunks of something like 50ms .. 2s based on
an onset detector, then captured the 2D time-frequency envelope
(nonuniformly sampled to give greater detail around the onsets) with 12
principal components, to give the 12D timbre feature.  Frequency content
was similarly analyzed within the segment to give the 12D chroma feature.

There is, unfortunately, no source code available for converting audio into
these features.  At the time, we expected the Echo Nest to continue to
support their analyze service for the foreseeable future (which turned out
to be about 5 years).  But I wrote an approximate reconstruction routine in
Matlab, en_resynth.m
<https://github.com/tbertinmahieux/MSongsDB/blob/master/MatlabSrc/en_resynth.m>,
which can be mined for an explanation of the structure of the features.

  DAn.

**Comment by marikgoldstein** [comment]
Thanks so much for your explanation and your code. They are helpful.

I also am reading through Sander Dieleman's thesis, and some more info on normalization can be found there.

Next step is to figure how this all relates to these timbre/pitch features:
https://developer.spotify.com/web-api/get-audio-analysis/

They match Sander's description of the older Echonest features. Will see what I can find out, and if there is any OK way to build from the Spotify API.

Closing the issue, and looking forward to finding out more.

mark

**Comment by dpwe** [comment]
The Spotify audio analysis API sounds exactly like the Echo Nest Analyze.
The only question is how closely the actual implementations match.  For
instance, they could have modified the time or frequency sampling of the
spectral envelope, and ended up with an entirely new set of PCA bases.

It would be great to run the audio for some known track in the MSD through
the Spotify audio analysis API and see how closely the features match those
from the MSD, and would be a big service to the community if you feel like
taking it on!

Best,

  DAn.

**Comment by marikgoldstein** [comment]
I'm up for the project. At a first look I've observed some funny connections...
Putting my starting thoughts on the matter below, but will probably move this to a better place than a closed Issue.

**Million Song Dataset and Spotify API both include analysis sample rate and segment timing info.**

Million Song Dataset info per track
https://labrosa.ee.columbia.edu/millionsong/pages/field-list
https://labrosa.ee.columbia.edu/millionsong/pages/example-track-description

Spotify API info per track
https://developer.spotify.com/web-api/get-track/
https://developer.spotify.com/web-api/get-audio-analysis/

**Steps to take:**
- find out if there is a clear relationship between "segment" definitions between the two datasets. Look into tracks available from both sources.
- find out the best way to confirm that you are looking at the same audio in both datasets. MSD has 7digital track ID and some MusicBrainz info. Spotify doesn't have these, but tracks do have an external IDs field that typical only brings up [isrc](https://musicbrainz.org/doc/ISRC). So far I have been doing this manually by looking for matching durations and album titles.
- Derive time-synced or beat-aligned features. This will be more useful than segment-synced features for finding the connection between the data sets, if segments are not the same.

**Regarding Building New Dataset**
The API call for audio analysis for a single track takes multiple seconds. On the other hand, if Spotify follows through with [this request for the API to support multiple track audio analysis with a single call](https://github.com/spotify/web-api/issues/366), maybe there will be smaller overhead. Unsure about Spotify terms of usage.

**ps**
Meanwhile, will experiment with MSD genre classification by drawing from some techniques for [sentence classification](http://www.aclweb.org/anthology/D14-1181) and [sentence summarization](http://nlp.seas.harvard.edu/papers/naacl16_summary.pdf) using CNNs used by [harvardNLP](http://nlp.seas.harvard.edu/).

Mark
